### ISSUE TITLE
error on install 

### ISSUE THREAD

**Issue by svangoor** [andresmrg/local_coursetocal#4] opened 2020-12-18 21:31 UTC
Hey there,
installed this plugin, installation seems okay. but after install and reopening site settings. 
syntax error, could not go to settings. 

Any idea what to do.

Moodle install 3.8.5

<img width="1430" alt="Schermafbeelding 2020-12-18 om 22 26 30" src="https://user-images.githubusercontent.com/72457387/102663209-9ff22d00-4180-11eb-9faa-77b358e3e6fa.png">

**Comment by iorobertob** [comment] 2021-01-07 20:31
@svangoor There is an extra "," (comma) on line 70 of file local/coursetocal/settings.php at the end arguments of new admin_setting_configempty constructor. I remove it and the problem is gone. I could make a pull request, but is just a comma!! :P maybe is easier for maintainers to do so?

**Comment by andresmrg** [comment] 2021-01-07 21:26
Resolved with the commit 550283c ... Download the latest version and re-install

**Comment by svangoor** [comment] 2021-01-09 11:29
Thanks guys,
Seems to install and work correct now, brilliant. !!

**Closed as completed** 2021-01-09 17:55 UTC
