### ISSUE TITLE
Error upon installing new version 3.9 20201212

### ISSUE THREAD

**Issue by argwallace** [andresmrg/local_coursetocal#3] opened 2020-12-14 09:55 UTC
Hello!

I just tried to update to the newer 3.9 version (I'm running 3.8.4) and I get an error every time I try to update or reinstall. The error is an exception error relating to a ')'. I was looking for an earlier version but I didn't see which one to download.

Thanks.

**Comment by andresmrg** [comment] 2020-12-14 15:37
Would you provide a screenshot or more details (debug mode on) about the error message that you are receiving?

**Comment by argwallace** [comment] 2020-12-14 18:56
Sure! I just tried installing again and I am still getting errors. Here is a screenshot of the errors:

**Comment by andresmrg** [comment] 2020-12-15 15:29
Hi @argwallace I did not see the image attached in the issue. Would you re-attempt to upload it? I'll proceed to install it in a brand new 3.8.4 to attempt to replicate the issue.

Thanks.

**Comment by argwallace** [comment] 2020-12-15 15:31
Here you go!

**Comment by andresmrg** [comment] 2020-12-15 15:33
The images are not being kept... would you send me the screenshot to andres.ramos@lmsdoctor.com or use a service like lightshot or dropdbox where you can share the link?

**Comment by iorobertob** [comment] 2021-01-07 20:32
hello @andresmrg @argwallace  
There is an extra "," (comma) on line 70 of file local/coursetocal/settings.php at the end arguments of new admin_setting_configempty constructor. I remove it and the problem is gone. I could make a pull request, but is just a comma!! :P maybe is easier for maintainers to do so?

**Comment by andresmrg** [comment] 2021-01-07 21:25
Done, it is fixed on the commit 550283c

**Comment by andresmrg** [comment] 2021-01-08 18:15
@argwallace Please check the latest version and confirm it works as expected.

**Comment by argwallace** [comment] 2021-01-08 18:41
Yes, I installed today and it works just fine. Thank you.

**Closed as completed** 2021-01-09 17:55 UTC
